### ISSUE TITLE
Should document CollectD integration

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#297]
The best way to integrate CollectD with InfluxDB is to use the OpenTSDB plugin that it has and the associated input plugin on InfluxDB. Please to document, ask @nathanielc for more details if you need help since he's implemented it :)

**Comment by nathanielc** [comment]
Collectd has a `write_tsdb` plugin that uses the OpenTSDB protocol to send data. Using this plugin is necessary to get tags from CollectD since CollectD's native protocol doesn't support tags.

This PR on collectd https://github.com/collectd/collectd/pull/1107 adds extra support to the `write_tsdb` plugin so that you can add tags and manipulate  the identifier/tag sets via config.

**Comment by dswarbrick** [comment]
@pauldix Can you elaborate on why you consider this method preferable to using the native collectd UDP protocol?

**Comment by nathanielc** [comment]
@dswarbrick The main reason is that the native collectd UDP protocol doesn't support tags. So there is now way to get custom tags on measurements  if you use it. 

Using the `write_tsdb` plugin for collectd enables that behavior.

For example telegraf has  a section in its config called **tags** and you can set arbitrary tags so that all metrics coming from that host have those tags. With the native collectd protocol there is no way to do that.

**Comment by paulstuart** [comment]
Does this mean that the collectd service is deprecated?

https://influxdb.com/docs/v0.9/write_protocols/collectd.html

**Comment by nathanielc** [comment]
@paulstuart, no

**Comment by otoolep** [comment]
+1 on that, it is fully supported.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/657aa5a1348ebde47446de0fb4c43ac102602185
