### ISSUE TITLE
document TOP()

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#319]
See https://github.com/influxdb/influxdb/issues/1821 for details on the syntax.

**Comment by corylanou** [comment]
`bottom` is coming right behind it :-).

**Comment by brettdh** [comment]
Why is the implementation in 0.9.4 but the doc slated for 0.9.5? This seems like a bad habit, and a microcosm of the way InfluxDB doc tends to lag the releases.

I hope this doesn't come across whiny; it's just been a concern of mine for a while.

**Comment by corylanou** [comment]
@brettdh It's a concern of ours as well.  I wrote `top` and it is a fairly complicated function with a lot of edge case scenarios.  We are working hard to keep docs up to date, but the only other option would of been to delay releasing the feature because the docs were not ready.  I think it's better to get the functionality out sooner than later, knowing that we are not ignoring docs, but docs take time.

If you have any questions on how to use `top` before we have the docs ready, please post them on the [mailing list](https://groups.google.com/forum/#!forum/influxdb) and we'll get you an answer as soon as we can.

**Comment by beckettsean** [comment]
will be closed by #455
