### ISSUE TITLE
describe why clusters must be at least three machines, not two

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#537]
@pauldix I think you are best able to elucidate this. Let's chat and then my team can write it up.

**Comment by pauldix** [comment]
Raft requires it. Any distributed consensus system requires at least 3 nodes. But of course we can chat more about it :)

**Comment by beckettsean** [comment]
Sure, I know that, but WHY? See https://groups.google.com/d/msgid/influxdb/CANNH9msg5ARvAitXBc6c0KY5JTmNu5aaP5GLo%2BBX%2Bhh2pmv5PA%40mail.gmail.com for more context.

I mean, with two nodes the system can function. There's only a deadlock chance if the two nodes disagree about a system-level add/modify/remove database, user, CQ, or RP.

If one machine of a two node cluster goes down, the other machine cannot promote itself to leader, right? Because there's no way to get a majority of the votes, only 50%. I think that's the fundamental reason consensus clusters need to be 3+, but are there other considerations?

**Comment by pauldix** [comment]
The 3 node requirement is so that a single failure can be tolerated. It's possible to achieve consensus in a 2 node configuration, but only if both nodes are up.

Basically, there's no point in having a 2 node cluster because if any one of them goes down, the other one will be down.

So why bother with a 2 node cluster?

**Comment by beckettsean** [comment]
Add to the clustering guide
